image: macos-sonoma

environment:
  PYTHON_VERSION: 3.12.4
  GITHUB_TOKEN:
    secure: 123

build:
- make iOS
- tar -czf python-ios-install-$PYTHON_VERSION.tar.gz install support -C .
- find dist -type f -iname python-ios-install-*.tar.gz -exec appveyor PushArtifact -DeploymentName python-ios-install {} \;

test: off

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  release: $(PYTHON_VERSION)
  artifact: python-ios-install
  on:
    APPVEYOR_REPO_TAG: true