image: macos-sonoma

skip_tags: true

environment:
  PYTHON_VERSION: 3.12
  GITHUB_TOKEN:
    secure: 9SKIwc3VSfYJ5IChvNR74iXakJ8p90REGx8NmYiuH6wClbWAAqQrRUkf4eyWT/DKtrRNlGxqv/8CGJr5qaqZaAQRVTXpb10aVqEbsUebe5EHCdj0ujLaJ4YOhL979/w5

install:
- git clone --branch=$PYTHON_VERSION https://github.com/beeware/Python-Apple-support.git

build_script:
# Build Python for iOS and macOS
- mkdir -p dist
- sh: |
    pushd Python-Apple-support
    make iOS || exit 1
    tar -czf ../dist/python-ios-mobile-forge-$PYTHON_VERSION.tar.gz install support -C .
    make macOS || exit 1
    popd

# Package for Dart
- ./package-ios-for-dart.sh Python-Apple-support $PYTHON_VERSION

# Push all archives to artifacts
- find dist -maxdepth 1 -type f -iname python-*.tar.gz -exec appveyor PushArtifact -DeploymentName python-darwin {} \;

test: off

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  release: v$(PYTHON_VERSION)
  artifact: python-darwin