image: macos-sonoma

skip_tags: true

environment:
  PYTHON_VERSION: 3.12.4
  GITHUB_TOKEN:
    secure: 9SKIwc3VSfYJ5IChvNR74iXakJ8p90REGx8NmYiuH6wClbWAAqQrRUkf4eyWT/DKtrRNlGxqv/8CGJr5qaqZaAQRVTXpb10aVqEbsUebe5EHCdj0ujLaJ4YOhL979/w5

build_script:
- make iOS
- tar -czf python-ios-install-$PYTHON_VERSION.tar.gz install support -C .
- find . -maxdepth 1 -type f -iname python-ios-install-*.tar.gz -exec appveyor PushArtifact -DeploymentName python-ios-install {} \;

test: off

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  release: v$(PYTHON_VERSION)
  artifact: python-ios-install